### ISSUE TITLE
why icub will break down?

### ISSUE THREAD

**Issue by 0707yiliu** [robotology/icub-basic-demos#24] opened 2020-07-28 10:04 UTC
I change the parameter in redballdemos configuration file config.ini and pf3dTracker.ini

when i give icub a red ball, it will broken down sometime. 

And today its torso motor suddenly cut itself off and bacame unuseable.

**Comment by pattacini** [comment] 2020-07-28 12:45
Hi @tKsome 

For getting help on how to deal with the broken cable, you should open up a dedicated ticket at https://github.com/robotology/icub-tech-support.

For why the robot misbehaved while performing the red-ball task, there might be multiple reasons, including the ball shape, false-positive detections of the ball, the reaching offsets, the speed of the movements, wrong conf files loaded at startup, and the like.

My recommendation is always approaching the demo incrementally:
- configure the demo to use only the head by [disabling the arms][1] so that it's safer to check whether the ball gets correctly localized (it should be displayed within the iCubGui).
- check if the conf files we've customized are those actually loaded at startup.
- enable only one arm and make the robot move slowly by increasing the [traj_time][2] to something like 3.0 s.

Anyway, be always ready to press the fault-button in time to prevent the robot from colliding with itself or from doing weird things.

[1]: https://github.com/robotology/icub-basic-demos/blob/master/demoRedBall/app/conf/config.ini#L5-L6
[2]: https://github.com/robotology/icub-basic-demos/blob/master/demoRedBall/app/conf/config.ini#L7

**Comment by 0707yiliu** [comment] 2020-07-29 02:29
This method is right. And i have complicated the first two steps.

When we were doing the red ball tracking experiment, icub sometimes wrote the red ball on its head, which lead the process broken down. In this pose, we cannot use robotmotorgui control the robotic motor.

I suspect it is the parameter configuration of tracker.

Here is my configuration
####################################
#configuration file for PF3DTracker#
####################################

#############
#module name#
#############
name /pf3dTracker

#############################
#parameters of the algorithm#
#############################
nParticles 600
#nParticles number of particles used
accelStDev 30
#accelStDev 50 30 15
#accelStDev standard deviation of the acceleration noise
insideOutsideDiffWeight 1.5
#insideOutsideDiffWeight inside-outside difference weight for the likelihood function
colorTransfPolicy 1
#colorTransfPolicy [0=transform the whole image | 1=only transform the pixels you need]

#########################
#port names and function#
#########################
inputVideoPort /pf3dTracker/video:i
#inputVideoPort receives images from the grabber or the rectifying program.
outputVideoPort /pf3dTracker/video:o
#outputVideoPort produces images in which the contour of the estimated ball is highlighted
outputDataPort /pf3dTracker/data:o
#outputDataPort produces a stream of data in the format: X, Y, Z, likelihood, U, V, seeing_object
outputParticlePort /pf3dTracker/particles:o
#outputParticlePort produces data for the plotter. it is usually not active for performance reasons.
inputParticlePort /pf3dTracker/particles:i
#inputParticlePort recives hypotheses on the ball position from pf3dBottomup.
outputAttentionPort /pf3dTracker/attention:o
#outputAttentionPort produces data for the attention system, in terms of a peak of saliency.

#################################
#projection model and parameters#
#################################
#projectionModel [perspective|equidistance|unified]
projectionModel perspective

cameraContext cameraCalibration
cameraFile icubEyes1.ini
cameraGroup CAMERA_CALIBRATION_LEFT

#######################
#tracked object models#
#######################
#trackedObjectType [sphere|parallelogram]
trackedObjectType sphere
#trackedObjectColorTemplate models/red_ball_iit.bmp
trackedObjectColorTemplate models/red_smiley_2009_07_02.bmp
#trackedObjectShapeTemplate models/initial_ball_points_36mm_20percent.csv
trackedObjectShapeTemplate models/shape_model_26_30.csv

motionModelMatrix models/motion_model_matrix.csv
trackedObjectTemp current_histogram.csv

#######################
#initialization method#
#######################
#initialization method [search|3dEstimate|2dEstimate]
initializationMethod 3dEstimate
initialX 0
initialY 0
initialZ 0.5

####################
#visualization mode#
####################
#circleVisualizationMode [0=inner and outer cirlce | 1=one circle with the correct radious] default 0. only applies to the sphere.
circleVisualizationMode 1

#########################
#attention-related stuff#
#########################
#the tracker produces a value of likelihood at each time step. this value can be used to infer if the object it is tracking is the correct one. this is not a very robust way of doing so.
#if likelihood>this value, then probably I'm tracking the object. 20Millions is good, 12Millions is the likelihood of Jonas Hornsteins's PC screen (false positive).
#20Millions is a good threshold level when you have the right color model. 5M.
likelihoodThreshold 0.0004
attentionOutputMax 250
attentionOutputDecrease 0.99

##########################
#image saving preferences#
##########################
#save images with OpenCV?
saveImagesWithOpencv false
#always use the trailing slash here.
saveImagesWithOpencvDir ./graphical_results/

**Comment by 0707yiliu** [comment] 2020-07-29 02:36
I checked the cable first yestoday and found no broken cable.

When i start-up the robotinterface properly today, the robot can run normally. I guess that after pressing the emergency stop button, the robotic electrical power will lose and its body will lean forward, causing it to fall an the torso.

**Comment by pattacini** [comment] 2020-07-29 07:02
>I checked the cable first yesterday and found no broken cable.

Good 👍🏻 

>When I start-up the robotinterface properly today, the robot can run normally. I guess that after pressing the emergency stop button, the robotic electrical power will lose and its body will lean forward, causing it to fall and the torso.

This is actually the intended behavior.

For what's left closing in favor of #25.

**Closed as completed by pattacini** 2020-07-29 07:02 UTC
Labels: help wanted
